FROM alpine:3.11

ENV PYTHON_VERSION=3.8.2-r0
ENV APP_PORT 8080
ENV BUILD_DIR /tmp/build
ENV BUTTERROBOT_VERSION 0.0.1

WORKDIR ${BUILD_DIR}
COPY poetry.lock ${BUILD_DIR}/poetry.lock
COPY pyproject.toml ${BUILD_DIR}/pyproject.toml
COPY ./butterrobot ${BUILD_DIR}/butterrobot
COPY ./butterrobot_plugins_contrib ${BUILD_DIR}/butterrobot_plugins_contrib
RUN apk --update add python3-dev==${PYTHON_VERSION} gcc musl-dev libffi-dev openssl-dev && \
    pip3 install poetry && \
    poetry build && \
    pip3 install ${BUILD_DIR}/dist/butterrobot-${BUTTERROBOT_VERSION}.tar.gz && \
    rm -rf ${BUILD_DIR}
COPY ./docker/bin/start-server.sh /usr/local/bin/start-server

CMD ["/usr/local/bin/start-server"]
