name: Distribute package

on:
  push:
    branches:
      - stable

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install -U poetry pip

    - name: Build and publish
      run: poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
